FROM rust:1.94-slim AS chef
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/sistema-fila /app/app
EXPOSE 8080
# Executa a aplicação
CMD ["./app"]
